namespace Decompiler.Enums
{
	  internal enum UGCType
	  {
		  UGC_TYPE_GTA5_MISSION = 0,
		  UGC_TYPE_GTA5_MISSION_PLAYLIST,
		  UGC_TYPE_GTA5_LIFE_INVADER_POST,
		  UGC_TYPE_GTA5_PHOTO,
		  UGC_TYPE_GTA5_CHALLENGE
	  }
}
